### ISSUE TITLE
Move from cryptonite to crypton

### ISSUE THREAD

**Issue by ocramz** [puffnfresh/haskell-jwt#5]
Apparently 'cryptonite' is not actively maintained, and 'crypton' is the new standard.

A number of key networking libraries have switched to 'crypton' already : https://packdeps.haskellers.com/reverse/crypton

It's API-compatible, so this should be just an import renaming chore.

**Comment by bmillwood** [comment]
- I attempted to do this and described the main blocker in #8

**Comment by puffnfresh** [comment]
Added a flag to do so: 2b3167c4522e435410337d9c0da4523ead26c345

I made it a flag since you already need a flag because of cryptostore. If https://github.com/ocheron/cryptostore/issues/13 gets resolved, I'll happily remove the flag.
